# Generated by Django 4.1 on 2023-11-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Addition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name="MapPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=127)),
                ("comment", models.TextField(blank=True, null=True)),
                ("address", models.CharField(max_length=255)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("addition", models.ManyToManyField(blank=True, to="pointer.addition")),
            ],
        ),
    ]
