# Generated by Django 4.1 on 2023-11-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pointer", "0002_mappoint_schedule_alter_mappoint_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapPointCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=127)),
            ],
        ),
    ]
