# Generated by Django 4.1 on 2023-11-10 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pointer", "0003_mappointcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappoint",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pointer.mappointcategory",
            ),
            preserve_default=False,
        ),
    ]
