# Generated by Django 4.1 on 2023-11-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pointer", "0004_mappoint_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mappointcategory",
            options={"verbose_name": "Map Point Categories"},
        ),
        migrations.AlterField(
            model_name="mappoint",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pointer.mappointcategory",
            ),
        ),
    ]
