# Generated by Django 4.1 on 2023-11-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pointer", "0005_alter_mappointcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mappointcategory",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
