# Generated by Django 4.1 on 2023-11-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pointer", "0006_alter_mappointcategory_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mappoint",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
