# Generated by Django 4.1 on 2023-11-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pointer", "0007_alter_mappoint_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addition",
            options={
                "verbose_name": "Особливість",
                "verbose_name_plural": "Особливості",
            },
        ),
        migrations.AlterModelOptions(
            name="mappoint",
            options={
                "verbose_name": "Точка на мапі",
                "verbose_name_plural": "Точки на мапі",
            },
        ),
        migrations.AlterModelOptions(
            name="mappointcategory",
            options={
                "verbose_name": "Категорія точки на мапі",
                "verbose_name_plural": "Категорії точок на мапі",
            },
        ),
        migrations.AlterField(
            model_name="addition",
            name="title",
            field=models.CharField(max_length=127, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="mappoint",
            name="addition",
            field=models.ManyToManyField(
                blank=True, to="pointer.addition", verbose_name="Особливості"
            ),
        ),
        migrations.AlterField(
            model_name="mappoint",
            name="address",
            field=models.CharField(
                default="Невідомо", max_length=255, verbose_name="Адреса"
            ),
        ),
        migrations.AlterField(
            model_name="mappoint",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pointer.mappointcategory",
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="mappoint",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Коментар"),
        ),
        migrations.AlterField(
            model_name="mappoint",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Затверджено"),
        ),
        migrations.AlterField(
            model_name="mappoint",
            name="latitude",
            field=models.FloatField(default=0.0, verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="mappoint",
            name="longitude",
            field=models.FloatField(default=0.0, verbose_name="Довгота"),
        ),
        migrations.AlterField(
            model_name="mappoint",
            name="schedule",
            field=models.CharField(
                blank=True, max_length=127, null=True, verbose_name="Розклад"
            ),
        ),
        migrations.AlterField(
            model_name="mappoint",
            name="source",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Джерело"
            ),
        ),
        migrations.AlterField(
            model_name="mappoint",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="mappointcategory",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Назва"),
        ),
    ]
